spring:
  application:
    name: INVENTORY-SERVICE
  datasource:
    url: jdbc:postgresql://inventory-db:5432/inventory_db
    username: inventory
    password: inventory
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8761/eureka

app:
  jwt-secret: aedcc9ba7b99c71aa607c0edd214c3f476b81ffd29c86ae85f7db93353d51f7f
  jwt-expiration-milliseconds: 604800000
